apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: reserve-request-service-deployment
  annotations:
    kubernetes.io/change-cause: "Initialized by manifest files."
  labels:
    env: production
    tier: backend
    app: reserve-request-service
    name: reserve-request-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production
      tier: backend
      app: reserve-request-service
      name: reserve-request-service-pod
  template:
    metadata:
      labels:
        env: production
        tier: backend
        app: reserve-request-service
        name: reserve-request-service-pod
    spec:
      containers:
        - name: reserve-request-service
          image: overpassion/egovframe-msa-backend-reserve-request-service:k8s # TODO
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SERVER_PORT
              value: "80"
            - name: APP_HOME
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: APP_HOME
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: EUREKA_URI
            - name: APIGATEWAY_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: APIGATEWAY_URI
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: SPRING_CLOUD_CONFIG_URI
            - name: MYSQL_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: MYSQL_HOSTNAME
            - name: ZIPKIN_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: ZIPKIN_HOSTNAME
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: RABBITMQ_HOSTNAME
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 36
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3